<div class="row">
	<div class="col-xs-12 text-center">
		<h1>TERMOS E CONDIÇÕES DA PRB MONZY</h1> 
	</div>
	<div class="col-xs-12 text-left">
		<h2>1. RELAÇÃO CONTRATUAL</h2>
		<p>Esses termos de uso (“Termos”) constituem um acordo legal entre pessoas que desejam contratar serviços Freelance (“treinadores”) e a PRB MONZY, uma empresa individual (coletivamente, “Monzy” ou “nós”), e entre os provedores de Serviços Free-lance aos Usuários (“clientes”) e a PRB MONZY. Estes termos regem o uso da nossa plataforma de serviços que facilita as comunicações entre Usuários e Freelancers, e é oferecido através do nosso site, no endereço www.monzy.com.br, segundo possa ser modificado, realocado ou redirecionado oportunamente, e os aplicativos móveis que oferecemos. Os nossos serviços, plataforma, site e aplicativos móveis são chamados coletivamente como “Site da Monzy”. Os termos “você”, “seu” ou “seus” se referem ao Usuário ou Freelancer segundo corresponda. O link do site é WWW.monzy.com.br.</p>
		               
		<h2>LEIA ESTES TERMOS COM ATENÇÃO ANTES DE COMEÇAR A UTILIZAR OS SERVIÇOS. Nestes termos, os termos “incluído/a(s)” e “incluir” significam “incluídos, a título enunciativo e não taxativo”.</h2>
		<p>O seu acesso e o uso que fizer do Site da Monzy constituem a sua aceitação de cumprir estes Termos, que estabelecem uma relação contratual entre você e a Monzy. Se não aceitar estes Termos, você não poderá acessar o Site da Monzy e nem utilizá-lo. Estes Termos substituem expressamente contratos ou acordos anteriores firmados com você. A Monzy poderá cancelar imediatamente estes Termos com respeito a você, ou em geral deixar de oferecer ou negar acesso ao Site da Monzy ou a qualquer uma de suas partes, a qualquer momento e por qualquer motivo.</p>                   
		<p>A Monzy poderá modificar os Termos relacionados com o Site da Monzy, oportunamente. As modificações terão validade no momento da publicação por parte da Monzy dos Termos atualizados nesta seção, ou das políticas modificadas ou os termos complementares do (dos) serviço(s) correspondente(s). Seu acesso ou uso contínuo do Site da Monzy depois desta publicação constitui o seu consentimento para estar sob os Termos e suas modificações:</p>
		<ul>
			<li>Sua aprovação quanto ao Site da Monzy ser oferecido “no estado em que se encontra” e sem nenhuma garantia;</li>
			<li>Sua aprovação de que o Site da Monzy é unicamente uma plataforma de comunicações que oferece um método para a contratação de Serviços Freelance, que todos os Serviços Freelance são realizados por terceiros e que a Monzy não tem responsabilidade alguma pelos Serviços Freelance ou pelos atos ou omissões de terceiros;</li>
			<li>Sua aprovação de liberar a Monzy de toda a responsabilidade que surja de reclamações relacionadas ao Site da Monzy ou de outro modo;</li>
			<li>Você concorda em manter a Monzy livre de reclamações que surjam do uso indevido ou da incapacidade de utilizar o Site da Monzy ou os Serviços Free-lance;</li>
			<li>Seu consentimento de que qualquer uma das partes tem o direito de recorrer a uma arbitragem obrigatória;</li>
			<li>Você aceita que nenhuma reclamação poderá ser julgada como demanda coletiva;</li>
			<li>Você consente a respeito da captura, utilização, divulgação e transferência dos seus dados conforme indicado na Política de Privacidade, com as suas oportunas modificações.</li>
		</ul>

		<h3>a. A  APLICAÇÃO É APENAS UM ESPAÇO.</h3>
		<p>O Site da Monzy é um mercado informático onde os Usuários e Freelancers podem se identificar e comprar e vender serviços online. Estes serviços específicos solicitados pelos Usuários, que devem ser realizados pelos Freelancers, são denominados adiante, “Serviços Freelance”. Em conformidade com os termos deste Acordo, a Monzy oferece serviços aos Usuários e Freelancers, incluindo o hosting e a manutenção do Site da Monzy, e permite a celebração de contratos entre Usuários. Quando um usuário e um Freelancer celebram um Contrato entre Usuários em conformidade com a subseção B a seguir, o Usuário e o Freelancer utilizam o Site da Monzy para se comprometer, comunicar-se, faturar e pagar online.</p>
		<p>A menos que a Monzy indique o contrário em um acordo escrito a parte com você, o Site da Monzy se coloca a disposição unicamente para o seu uso pessoal e não comercial. A Monzy não presta Serviços Freelance por si mesma. A prestação de todos os Serviços Free-lance depende dos Freelancers. A MONZY, ATRAVÉS DE SUA APLICAÇÃO, OFERECE INFORMAÇÃO E UM MÉTODO PARA OBTER ESTES SERVIÇOS DE FORMA FREELANCE, PORÉM, NÃO TEM RESPONSABILIDADE ALGUMA PELOS SERVIÇOS FREELANCE E/OU PELO PRODUTO DE TRABALHO QUE OS FREELANCERS ANUNCIEM NO SITE, E ENTREGUEM AOS USUÁRIOS, INCLUÍDAS, A TÍTULO ENUNCIATIVO E NÃO TAXATIVO, AS GARANTIAS DE IDONEIDADE PARA UM DETERMINADO FIM OU CUMPRIMENTO DE LEIS, REGULAMENTAÇÕES OU CÓDIGOS. A MONZY NÃO ESTÁ AFILIADA, RESPALDADA E NEM PATROCINADA POR NENHUM PROVEDOR EXTERNO.</p>

		<h3>b. SERVIÇOS ENTRE USUÁRIOS.</h3>
		<p>Você é o exclusivo responsável de assegurar o cumprimento de suas obrigações frente aos Freelancers. Se não o fizer, é possível que seja responsável diante do Freelancer em questão. Deve se assegurar de conhecer todas as leis nacionais, leis internacionais, normas, ordenanças e regulamentações relativas a você como Usuário ou a qualquer outro que se utilize do Site da Monzy.</p>
		<p>Se um Freelancer não cumpre com alguma obrigação frente a você, ou causa danos a você, a sua propriedade ou aos seus direitos, você é o único responsável de exercer os direitos que poderia ter. Para evitar qualquer dúvida, nós não temos nenhuma responsabilidade de exercer direitos em virtude de um Contrato entre Usuários ou de danos à sua pessoa, propriedade ou seus direitos causados por um Freelancer.</p>
		<p>Em função de sua jurisdição, os Usuários e Freelancers podem ter direitos em virtude de garantias legais que não podem ser excluídas legalmente. Nenhum destes Termos pretende invalidar os direitos que não possam ser excluídos segundo a legislação aplicável.</p>
		<p>Cada Usuário e Freelancer reconhecem e aceita que a relação entre o Usuário e qualquer Freelancer corresponde a de um contratante independente. Nenhuma das disposições destes Termos cria uma associação, empresa conjunta, agência ou relação de emprego entre Usuários e Freelancers. Nenhuma das disposições destes Termos deverá ser interpretada como se constituísse uma empresa conjunta, uma associação ou uma relação empregador-empregado entre a Monzy e algum Usuário ou Freelancer.</p>
		<p>Cada freelancer (ou professor/orientador/instrutor, como ficar acertado na relação entre os usuários), deverá se comprometer com seus usuários (ou aluno/orientando) o período acordado, ou seja, deverá cumprir integralmente o número de aulas acertadas, retomando aulas interrompidas por quaisquer motivos. </p>
		               
		<h3>c. VETO DE USUÁRIOS.</h3>
		<p>Os Freelancers podem estar sujeitos a um processo de veto antes de poder se registrar durante o uso que façam do Site da Monzy. A Monzy poderá realizar verificações de antecedentes dos Freelancers, mas não poderá confirmar se cada Freelancer é quem declara ser e, portanto, não pode assumir e nem assume nenhuma responsabilidade pela precisão ou veracidade da identidade, pela informação da verificação de antecedentes ou pela informação proporcionada através do Site da Monzy.</p>
		<p>A empresa PRB MONZY poderá oferecer premiações aos treinadores que obtiverem melhores desempenhos pela avaliação de seus respectivos alunos. Os treinadores precisam ter avaliações acima de 03 (três) estrelas e ministrar, no mínimo, 50 (cinquenta) aulas por mês para receberem prêmios. A empresa fará a divulgação aos treinadores quando iniciar as premiações.</p>
		<p>AO UTILIZAR A APLICAÇÃO DA MONZY, VOCÊ ACEITA LIBERAR A MONZY DE TODA A RESPONSABILIDADE OU DANO QUE POSSA SURGIR A PARTIR DOS SERVIÇOS PROFISSIONAIS. A EMPRESA NÃO É RESPONSÁVEL PELA CONDUTA, SEJA ONLINE OU NÃO, DE NENHUM USUÁRIO, INCLUINDO OS PROVEDORES EXTERNOS, E NÃO SERÁ RESPONSÁVEL POR NENHUMA RECLAMAÇÃO, LESÃO OU DANO QUE SURJA EM RELAÇÃO AOS SERVIÇOS FREELANCE.</p>

		<h3>d. LICENÇA.</h3>
		<p>Sujeito ao cumprimento destes Termos, a Monzy lhe outorga uma licença limitada, não exclusiva, não sublicenciável, revogável e intransferível para: (i) acessar e utilizar o Site da Monzy em seu dispositivo pessoal unicamente em relação com o seu uso e (ii) acessar e utilizar qualquer conteúdo, informação e materiais relacionados que possam estar disponíveis através do Site da Monzy, em cada caso unicamente para o seu uso pessoal e não comercial. A empresa Monzy e os licenciadores da Monzy se reservam todos os direitos que não se outorguem expressamente no presente contrato.</p>

		<h3>e. RESTRIÇÕES.</h3>
		<p>Você não poderá: (i) eliminar avisos de direitos autorais ou marcas comerciais ou outro aviso de propriedade intelectual de nenhuma parte do Site da Monzy; (ii) reproduzir, modificar, criar obras derivadas, distribuir, licenciar, alugar, vender, revender, transferir, mostrar publicamente, apresentar publicamente, transmitir, publicar, difundir ou explorar de qualquer outra maneira o Site da Monzy, exceto segundo o permitido expressamente pela empresa proprietária; (iii) descompilar, realizar engenharia inversa ou desarticular o Site da Monzy, exceto segundo o permitido pela legislação aplicável; (iv) vincular, duplicar ou utilizar marcos em nenhuma parte do Site da Monzy; (v) introduzir ou implementar programas ou sequências de comandos a fim de extrair informação, indexar, esquadrinhar ou de outro modo realizar mineração de dados em nenhuma parte do Site da Monzy, ou dificultar ou impedir indevidamente a operação e/ou funcionalidade de qualquer aspecto do Site; (vi) tentar obter acesso não autorizado ou afetar qualquer aspecto do Site da Monzy ou seus sistemas ou redes relacionadas.</p>

		<h3>f. PROPRIEDADE.</h3>
		<p>O Site da Monzy e todos os direitos estabelecidos ali são e continuarão sendo propriedade da empresa PRB MONZY ou dos licenciadores da Monzy. Nem estes Termos nem o uso que faça do Site lhe transferirão ou outorgarão direitos: (i) sobre o Site da Monzy ou relacionados com ele, exceto a licença limitada outorgada anteriormente; nem (ii) a utilizar ou fazer referência de alguma maneira aos nomes da companhia, logotipos, nomes de produtos e serviços, marcas comerciais ou marcas de serviços da Monzy ou seus licenciadores.</p>


		<h2>2. O USO DOS SERVIÇOS.</h2>

		<h3>a. CONTAS.</h3>
		<p>Para poder utilizar a maior parte do Site da Monzy, você deve se registrar e manter uma conta pessoal e ativa de serviços para usuários (“Conta”). Deve ter pelo menos 18 anos de idade, ou ter alcançado a maioridade legal em sua jurisdição (se esta não for 18 anos), para obter uma conta. O registro da conta requer que você envie determinada informação pessoal à empresa Monzy, como seu nome, endereço, número de telefone celular e idade, assim como também pelo menos um método de pagamento válido (um cartão de crédito ou um provedor de pagamentos aceito). Você aceita manter a informação exata, completa e atualizada em sua Conta. A falta de manutenção da informação da Conta exata, completa e atualizada, o que inclui contar com um meio de pagamento inválido ou vencido registrado, pode dar lugar a sua desabilitação para acessar e utilizar o Site da Monzy ou a rescisão deste Acordo com você por parte da empresa Monzy. Você é responsável por toda a atividade que tenha lugar em sua Conta, e aceita manter a segurança e confidencialidade do nome de usuário e a senha da sua Conta a todo o momento. A menos que a Monzy permita o contrário por escrito, você só pode ter uma Conta. Os perfis dos Freelancers devem refletir de forma precisa a experiência, as habilidades e a informação pessoal do Freelancer.</p>

		<h3>b. REQUISITOS E CONDUTA DO USUÁRIO.</h3> 
		<p>A idade mínima para utilização do site da Monzy, de acordo com a legislação brasileira é de 18 (dezoito anos completos), declarada pelo usuário no ato de sua inscrição. A Monzy aceitará usuários com idade superior à 15 (quinze anos completos), desde que devidamente autorizado por seus responsáveis.</p>
		<p>Os Freelancers e os usuários, assim definidos, deverão se tratar com respeito mútuo e urbanidade, sempre preservando as boas relações e a interação dentro do ambiente virtual.</p>
		<p>A Monzy se reserva o direito de suspender Freelancers e usuários que não observarem os requisitos acima descritos, ou que produzirem ofensas morais e palavras de baixo calão, a fim de preservar o bom relacionamento no ambiente virtual.</p>

		<h3>c. USO ACEITÁVEL.</h3> 
		<p>Durante a vigência deste Acordo, você poderá utilizar o Site da Monzy unicamente para o seu uso pessoal (ou para o uso de uma empresa ou outra organização, a qual você represente). Você poderá utilizar o Site para contratar Serviços Freelance apenas com respeito à localização onde se encontre legalmente autorizado para receber ou oferecer Serviços Freelance. Você não poderá utilizar o Site para nenhum outro fim ou em relação a qualquer outra atividade comercial sem o nosso consentimento expresso previamente por escrito. Você não poderá utilizar o Site da Monzy violando leis, normas, ordens ou regulamentações. Você aceita que uma solicitação de Serviços Freelance constitui uma oferta, que se considera aceita apenas quando recebe uma confirmação da solicitação. Você aceita que tratará os Freelancers de maneira cortês e legal, e que cooperará razoavelmente com os Freelancers para permitir que ofereçam os Serviços Freelance. Os Freelancers aceitam que oferecerão os Serviços Freelance uma vez que tenham aceitado uma solicitação de maneira profissional e com garantia de qualidade, e que prestação estes serviços de maneira cortês e legal, e fazendo o melhor uso de suas habilidades, e que aceitação as solicitações apenas se o Freelancer estiver qualificado e for capaz de realizar tais Serviços Freelance.</p>
		<p>O Site da Monzy pode conter perfis, sistemas de e-mail eletrônico, blogs, quadros de mensagens, solicitações, anúncios de trabalhos, áreas de chat, grupos de notícias, fóruns, comunidades e/ou outros espaços para mensagens ou comunicações (“Áreas da Comunidade”) que lhe permitem se comunicar com outros usuários. Você pode utilizar estas áreas da comunidade unicamente para enviar e receber mensagens e materiais que sejam pertinentes e apropriados em função de cada fórum em particular. Você NÃO deverá usar o Site da Monzy (incluída, a título enunciativo e não taxativo, qualquer Área da Comunidade) para fazer o seguinte:</p>

		<ul>
		<li>Difamar, abusar, acusar, atacar, ameaçar ou violar de outra maneira direitos legais (como por exemplo, os direitos de privacidade e publicidade, entre outros) de outras pessoas, incluindo o pessoal da empresa PRB MONZY. </li>
		<li>Publicar, anunciar, subir, distribuir ou disseminar tópicos, nomes, materiais ou informações indecentes, difamatórias, transgressoras, obscenas ou ilegais, nem materiais, informações ou conteúdo que envolvam a venda de artigos falsificados ou roubados. </li>
		<li>Utilizar o Site da Monzy ou os Serviços Freelance para qualquer fim ou de qualquer maneira que viole a legislação local, estatal, nacional ou internacional. </li>
		<li>Subir arquivos que contenham software ou outro material que viole direitos de propriedade intelectual (ou direitos de privacidade ou publicidade) de terceiros. </li>
		<li>Subir arquivos que contenham vírus, trojans, arquivos corruptos ou qualquer outro software similar que possa causar dano à operação de outro computador. </li>
		<li>Publicar ou subir conteúdo a respeito do qual não tenha obtido direitos ou permissões necessários para utilizá-lo. </li>
		<li>Publicitar ou oferecer a venda de qualquer produto ou serviço com fins comerciais através do Site da Monzy que não correspondam aos serviços oferecidos.</li>
		<li>Realizar ou enviar enquetes, concursos, esquemas pirâmides ou cartas em cadeia.</li>
		<li>Fazer-se passar por outra pessoa ou usuário, ou permitir que outra pessoa ou entidade utilize a sua identidade para publicar ou ver comentários ou utilizar a sua conta de outra maneira. </li>
		<li>Publicar a mesma nota repetidamente (mensagens lixo ou “Spam”). O envio de Spam está estritamente proibido. </li>
		<li>Baixar arquivos publicados por outros usuários quando o usuário tiver ou razoavelmente devesse ter conhecimento de que não possam ser distribuídos legalmente através do Site da Monzy.</li>
		<li>Restringir ou inibir outros usuários para que não possam utilizar e desfrutar das Áreas da Comunidade. </li>
		<li>Insinuar ou afirmar que as declarações que você faz estão asseguradas pela empresa PRB MONZY, sem o prévio consentimento por escrito da mesma. </li>
		<li>Utilizar um robô, aranha web, processos manuais e/ou automáticos ou dispositivos para realizar mineração de dados, rastreamentos, extraírem informações ou indexar o Site da Monzy de alguma maneira.</li>
		<li>Hackear ou interferir no Site da Monzy, em seus servidores ou qualquer rede conectada. </li>
		<li>Adaptar, alterar, licenciar, sublicenciar ou traduzir o Site da Monzy para o seu próprio uso pessoal ou comercial. </li>
		<li>Eliminar ou alterar, visualmente ou de outro modo, direitos autorais, marcas comerciais de propriedade exclusiva e direitos de propriedade intelectual que são propriedade da empresa PRB MONZY. </li>
		<li>Subir conteúdo que seja ofensivo e/ou que cause danos, incluindo, a título enunciativo e não taxativo, conteúdo que defenda, assegure, aprove ou promova o racismo, a intolerância, o ódio ou o dano físico de qualquer classe contra indivíduos ou grupos de indivíduos.</li>
		<li>Subir conteúdo que ofereça materiais ou acesso a materiais que explorem pessoas menores de 18 anos de maneira abusiva, violente ou sexual. </li>
		<li>Utilizar o Site da Monzy para recrutar para outros negócios, sites ou serviços, ou entrar em contato de outro modo com os usuários para empregos, contratações ou outros fins não relacionados com o uso do Site, segundo o estabelecido no presente Contrato. </li>
		<li>Utilizar o Site da Monzy para recolher nomes de usuários e/ou endereços de e-mail de usuários por meios eletrônicos ou de outro tipo. </li>
		<li>Registrar-se com outro nome de usuário ou identidade depois que a sua conta tenha sido cancelada ou fechada.</li>
		</ul>

		<p>Você compreende que todas as publicações que realiza nas Áreas da Comunidade serão públicas e que você será identificado publicamente pelo seu nome ou identificação de início de sessão ao se comunicar nas Áreas da Comunidade, e que a empresa PRB MONZY não será responsável pela ação dos usuários a respeito de informações ou outros materiais publicados nas Áreas da Comunidade.</p>

		<h3>d. CÓDIGOS PROMOCIONAIS.</h3>
		<p>A empresa PRB MONZY poderá, em sua exclusiva discrição, gerar códigos promocionais que poderão ser trocados por  créditos nas Contas, ou outras características ou benefícios relacionados ao Site da Monzy e/ou os Serviços Freelance, em conformidade com os termos adicionais que a Monzy estabeleça segundo as bases de cada código promocional em particular (“Códigos Promocionais”). Você aceita que os Códigos Promocionais: (i) devem ser utilizados e a audiência previstos, e de maneira legal; (ii) não podem ser duplicados, vendidos ou transferidos de nenhuma maneira, nem serem colocados a disposição do público geral (seja anunciando-os de maneira pública ou de outra maneira), a menos que a empresa PRB MONZY o permita expressamente; (iii) podem ser desativados pela PRB MONZY a qualquer momento e por qualquer motivo sem que a mesma tenha alguma responsabilidade; (iv) só poderão ser utilizados em conformidade com os termos específicos que a PRB MONZY estabeleça para estes Códigos Promocionais; (v) não podem ser trocados por dinheiro vivo; e (vi) podem vencer antes do seu uso. A empresa PRB MONZY se reserva o direito de reter ou deduzir créditos ou outras características ou benefícios obtidos através do uso que você ou outro usuário faça dos Códigos Promocionais se a empresa determina ou considera que o uso ou troca dos Códigos Promocionais foi realizado de maneira incorreta, fraudulenta, ilegal ou violando os termos do Código Promocional correspondente ou destes Termos.</p>
		 
		<h3>e. DISPOSITIVOS E ACESSO A REDE.</h3>
		<p>Você é responsável por obter o acesso à rede de dados necessário para utilizar o Site da Monzy. Podem ser aplicadas taxas e os carregamentos de dados e mensagens de sua rede móvel se acessar ou utilizar o Site da Monzy a partir de um dispositivo com capacidade inalâmbrica. Você é responsável por adquirir e atualizar os dispositivos ou o hardware compatível necessário para acessar e utilizar as Aplicações e o Site da Monzy e qualquer atualização realizada neles. A PRB MONZY não garante que o Site ou qualquer uma de suas partes funcionarão em algum dispositivo ou hardware em particular. Mesmo assim, o Site pode apresentar um mau funcionamento ou atrasos inerentes ao uso da Internet e as comunicações eletrônicas.</p>

		<h3>f. PAGAMENTOS</h3>
		<p>O valor repassado para pagamento dos Freelancers será de R$ 10,15 (dez reais e quinze centavos) por hora de aula finalizada e por cada aluno atendido. Os repasses serão feitos até o dia 15 (quinze) do mês subsequente ao vencido (exemplo: aulas ministradas no mês de outubro serão repassadas até o dia 15 do mês de novembro e assim por diante). Para que o repasse seja efetuado, será necessário que o Freelance tenha ministrado, no mínimo, 10 (dez) aulas completas no mês. Caso não tenha atingido o mínimo, o valor será acumulado com o valor do mês seguinte, sendo pago no próximo.</p>
		<p>A cada aula completada, o instrutor receberá 350 MP (indexador estabelecido pela Monzy) – dos quais, 25% (vinte e cinco por cento) serão repassados para a empresa PRB MONZY, para o custeio e manutenção das despesas relativas ao site. Será transferido para a conta corrente cadastrada pelo Freelancer/instrutor/orientador no site, o valor equivalente aos MP convertido em reais. Não será concedido nenhum adiantamento. Não será devolvido qualquer valor após o usuário comprar pontos para utilizar o site.</p>

		<h2>3. PROPRIEDADE INTELECTUAL - DIREITOS AUTORAIS -  CONFIDENCIALIDADE</h2>

		<h3>a. DIREITOS DE PROPRIEDADE INTELECTUAL.</h3>
		<p>Todo o texto, a gráfica, o conteúdo editorial, os dados, o formato, os gráficos, os designs, a linguagem HTML, o aspecto e a aparência, as fotografias, a música, os sons, as imagens, o software, os vídeos, os tipos de letra e outro conteúdo (coletivamente, “Material Exclusivo”) que veja ou leia através do Site da Monzy é propriedade da empresa PRB MONZY, com exceção do Conteúdo que a Monzy tem o direito de usar segundo o descrito anteriormente. O Material Exclusivo está protegido em todas as suas formas, meios e tecnologias conhecidas atualmente ou desenvolvidas no futuro. A empresa Monzy é proprietária de todo o Material Exclusivo, assim como da coordenação, seleção, disposição e melhoria de tal Material Exclusivo como Obra Coletiva em virtude da Lei de Direitos Autorais do Brasil, com as suas modificações. O Material Exclusivo está protegido por leis nacionais e internacionais em matéria de direitos autorais, patentes e outros direitos e leis sobre propriedade intelectual. Você não pode copiar, baixar, utilizar, redesenhar, reconfigurar e nem retransmitir nenhum elemento do Site da Monzy sem o consentimento expresso previamente por escrito da PRB MONZY e, se corresponde, do titular dos direitos sobre o Conteúdo. Qualquer uso deste Material Exclusivo, exceto o que se permite em virtude do presente, está expressamente proibido sem a permissão prévia da empresa PRB MONZY e, se corresponde, do titular dos direitos sobre o Conteúdo</p>
		<p>As marcas de serviço e as marcas comerciais da empresa PRB MONZY, incluídas, a título enunciativo e não taxativo, “Monzy” e os logotipos da Monzy são marcas de serviço de propriedade da empresa PRB MONZY. Qualquer outra marca comercial, marca de serviço, logotipo e/ou nome comercial que apareça no Site da Monzy são propriedade de seus respectivos donos. Você não pode copiar e nem utilizar nenhuma destas marcas, logotipos ou nomes comerciais que aparecem no Site da Monzy sem o consentimento expresso prévio por escrito do proprietário</p>
		<p>A empresa PRB MONZY não está sujeita a pagamento de direitos autorais sobre o conteúdo fornecido no site, embora se reserve o direito a receber 30% (trinta por cento) do valor de produtos vendidos através do site da Monzy.</p>

		<h3>b. INFORMAÇÃO CONFIDENCIAL.</h3>
		<p>Você reconhece que a Informação Confidencial (segundo é definida a seguir) é um ativo valioso, especial e único da PRB MONZY e aceita que não divulgará, transferirá, utilizará (nem tentará induzir outros a divulgar, transferir ou utilizar) Informação Confidencial para fins que não sejam a divulgação a seus empregados e agentes autorizados que se encontram obrigados a manter a confidencialidade da Informação Confidencial. Você deverá notificar a empresa PRB MONZY por escrito imediatamente de qualquer circunstância que possa constituir uma divulgação, transferência ou uso não autorizado da Informação Confidencial. Você deverá fazer tudo o que for possível para proteger a Informação Confidencial. Você deverá realizar tudo o que for possível para proteger a Informação Confidencial da divulgação, transferência, ou uso não autorizado. Você deverá devolver todos os originais e qualquer cópia de materiais que contenham Informação Confidencial à empresa PRB MONZY no momento de extinção deste Acordo por qualquer motivo. O termo “Informação Confidencial” se referirá a todos os segredos comerciais e informação confidencial e de propriedade exclusiva da PRB MONZY e a toda outra informação e dados do seu site que, em geral, não sejam de conhecimento do público ou de terceiros que possam obter um valor, econômico ou de outro tipo, com seu uso ou divulgação. Será considerado que a Informação Confidencial inclui dados técnicos, know-how, estudos, planos de produtos, produtos, serviços, clientes, mercados, software, desenvolvimentos, invenciones, processos, fórmulas, tecnologia, designs, desenhos, engenharia, informação de configuração de hardware, marketing, finanças ou outra informação comercial divulgada direta ou indiretamente por escrito, de forma oral ou através de desenhos ou observações.</p>
		                              
		<h2>4. ISENÇÕES DE RESPONSABILIDADE -  LIMITAÇÃO DE RESPONSABILIDADE -  INDENIZAÇÃO</h2>

		<h3>a. LIMITAÇÃO DE RESPONSABILIDADE.</h3>
		<p>A PRB MONZY NÃO SERÁ RESPONSÁVEL POR DANOS INDIRETOS, INCIDENTAIS, ESPECIAIS, EXEMPLARES, PUNITIVOS OU CONSEQUENTES, ENTRE OS QUE SE INCLUEM A PERDA DE FUNDOS, A PERDA DE DADOS, LESÕES PESSOAIS OU DANOS À PROPRIEDADE, RELACIONADOS COM O USO DOS SERVIÇOS OU COMO CONSEQUÊNCIA DELE, INCLUINDO O CASO DE TER SIDO INFORMADA SOBRE A POSSIBILIDADE DE TAIS DANOS. </p>
		<p>A PRB MONZY TAMBÉM NÃO SERÁ RESPONSÁVEL POR DANOS, PREJUÍZOS OU PERDAS QUE SURJAM DE: (i) SUA PRESTAÇÃO, USO OU DEPENDÊNCIA DOS SERVIÇOS DO SITE DA MONZY, OU SUA INCAPACIDADE PARA ACESSAR OU UTILIZAR OS SERVIÇOS OFERECIDOS (ii) QUALQUER TRANSAÇÃO OU RELAÇÃO ENTRE O USUÁRIO E QUALQUER FREELANCER, MESMO NO CASO DE A EMPRESA PRB MONZY TER SIDO INFORMADA SOBRE A POSSIBILIDADE DE TAIS DANOS. A EMPRESA NÃO SERÁ RESPONSÁVEL PELO ATRASO OU INCUMPRIMENTO QUE RESULTE DE CAUSAS QUE EXCEDEM O CONTROLE RAZOÁVEL DA PRB MONZY. O USUÁRIO RECONHECE QUE É POSSÍVEL QUE OS FREELANCERS QUE OFERECEM SERVIÇOS FREELANCE NÃO CONTEM COM LICENÇAS OU AUTORIZAÇÕES PROFISSIONAIS. EM NENHUM CASO A RESPONSABILIDADE TOTAL DA PRB MONZY FRENTE A VOCÊ EM RELAÇÃO AOS SERVIÇOS POR TODOS OS DANOS, PERDAS E CAUSAS DE AÇÃO EXCEDERÁ OS ENCARGOS TOTAIS PAGOS OU RECEBIDOS POR VOCÊ ATRAVÉS DO SITE DA MONZY, DURANTE OS SEIS (6) MESES ANTERIORES NO MOMENTO EM QUE SE APRESENTOU A RECLAMAÇÃO.</p>
		<p>OS SERVIÇOS OFERECIDOS PELO SITE DA MONZY PODEM SER UTILIZADOS PELO USUÁRIO PARA SOLICITAR E PROGRAMAR PRODUTOS OU SERVIÇOS DE LOGÍSTICA COM OS FREELANCERS, MAS VOCÊ ACEITA QUE A PRB MONZY NÃO TEM RESPONSABILIDADE ALGUMA FRENTE A VOCÊ EM RELAÇÃO A PRODUTOS OU SERVIÇOS DE LOGÍSTICA OFERECIDOS AO USUÁRIO PELOS FREELANCERS OU COM RESPEITO AO USO DOS SERVIÇOS FREELANCE POR PARTE DO USUÁRIO (INCLUINDO A FALTA DE PAGAMENTO) MAIS QUE A QUE SE ESTABELECE EXPRESSAMENTE NESTES TERMOS.</p>
		<p>AS LIMITAÇÕES E A ISENÇÃO DE RESPONSABILIDADE QUE SE ESTABELECEM NESTA SEÇÃO QUATRO NÃO PRETENDEM LIMITAR A RESPONSABILIDADE NEM ALTERAR OS DIREITOS DO USUÁRIO COMO CONSUMIDOR, QUE NÃO PODEM SER EXCLUÍDOS EM VIRTUDE DA LEGISLAÇÃO APLICÁVEL.</p>


		<h3>b. INDENIZAÇÃO.</h3>
		<p>Você aceita liberar de qualquer responsabilidade e manter isenta a empresa PRB MONZY e seus executivos, diretores, funcionários e agentes de qualquer reclamação, demanda, perda, responsabilidade e gasto (incluindo, a título enunciativo e não taxativo, os honorários de advogados) que surjam ou se relacionem com: (i) seu uso do Site da Monzy ou os serviços ou produtos obtidos ou proporcionados ou vendidos através do Site, incluindo qualquer conteúdo transmitido ou recebido por você, ou o acesso ou uso do Site por um terceiro com o seu nome de usuário e senha; (ii) seu descumprimento ou violação de qualquer um destes Termos ou de leis, normas ou regulamentações aplicáveis (incluindo, a título enunciativo e não taxativo, as leis em matéria impositiva ou profissional); (iii) o uso do seu Conteúdo por parte da PRB MONZY; (iv) sua violação de direitos de terceiros, incluindo Freelancers e Usuários.</p>

		<h2>5. DISPUTAS COM A PRB MONZY</h2>

		<h3>a. DISPENSA DE JULGAMENTO.</h3>
		<p>Você aceita que qualquer disputa, reclamação ou controvérsia que surja destes Termos ou em relação com eles ou com o descumprimento, a extinção, a aplicação, a interpretação, ou a validade destes Termos ou o uso do Site da Monzy (coletivamente, “Disputas”) se resolverá mediante uma arbitragem vinculante entre você e a PRB MONZY, com exceção de que cada parte se reserva o direito de iniciar uma ação individual em um tribunal de questões menores e o direito de solicitar medidas precatórias ou outros recursos de equidade em um tribunal de jurisdição competente para evitar a infração real ou potencial, a apropriação indevida ou a violação de direitos autorais, marcas comerciais, patentes ou outros direitos de propriedade intelectual de alguma das partes. Você reconhece e aceita que você e a empresa PRB MONZY estão renunciando o direito de juízo por jurado ou a participar como requerente ou parte de qualquer demanda coletiva ou ação representativa que se pretenda. Assim mesmo, a menos que você e a PRB MONZY acordem o contrário por escrito, o árbitro não poderá consolidar as reclamações de mais de uma pessoa e também não poderá resolver sobre demandas coletivas ou ações representativas de nenhum tipo. Se este parágrafo em particular for considerado inválido, então a totalidade desta seção de “Resolução de Disputas” será considerada nula. Exceto segundo o indicado na anteriormente, esta seção de “Resolução de Disputas” continuará vigente depois da extinção destes Termos.</p>

		<h3>b. NEGOCIAÇÃO INFORMAL.</h3>
		<p>Para acelerar a resolução e reduzir o custo de qualquer disputa, controvérsia ou reclamação relacionada com este Acordo ou que surja de alguma outra maneira da relação entre você e a PRB MONZY, você aceita como primeira tentativa negociar qualquer disputa de maneira informal durante pelo menos trinta (30) dias antes de iniciar qualquer arbitragem ou procedimento judicial. Estas negociações informais começarão mediante notificação escrita. O seu endereço aos efeitos destas notificações será o endereço indicado em sua conta no site da Monzy.</p>


		<h2>6. OUTRAS DISPOSIÇÕES</h2>

		<h3>a. LEGISLAÇÃO APLICÁVEL.</h3>
		<p>Estes Termos serão regidos e interpretados em conformidade com as leis brasileiras.</p>

		<h3>b. NOTIFICAÇÕES.</h3>
		<p>A PRB MONZY poderá enviar notificações mediante uma notificação geral no seu Site, por e-mail para o endereço de e-mail que figura em sua Conta ou através de uma comunicação escrita enviada por correio certificado ou com postagem pré-paga para o endereço que figura em sua Conta. Estas notificações serão consideradas cursadas ao vencimento do prazo de 48 horas após o despacho por correio ou postal (no caso do envio pelo correio certificado ou com postagem pré-paga) ou de 12 horas após o envio (no caso do envio por e-mail).</p>

		<h3>c. DISPOSIÇÕES GERAIS.</h3>
		<p>Você não pode ceder estes Termos sem a aprovação prévia por escrito da PRB MONZY. A empresa PRB MONZY poderá ceder estes Termos sem o seu consentimento a: (i) subsidiárias ou afiliadas; (ii) adquirentes de capital, do negócio ou ativos da PRB MONZY; o (iii) sucessores por fusão. Qualquer tentativa de cessão que não cumpra com esta seção será nula. Não existe nenhum tipo de empresa conjunta, associação, relação de emprego ou relação de agência entre você e a PRB MONZY como consequência deste Acordo ou o uso do Site da Monzy. Se alguma disposição destes Termos for considerada inválida ou inaplicável, tal disposição será eliminada e o resto das disposições conservação sua validade na máxima medida que a lei o permita. O fato de que a PRB MONZY não exerça algum direito ou disposição nestes Termos não constituirá uma renúncia a tal direito ou disposição, a menos que a empresa o reconheça e aceite por escrito.</p>
		 
	</div>

	<div class="col-xs-12 text-left">
		@lang('site.terms.accept_text')
	</div>

</div>